"""Regenerate src/voLines.ts from scripts/tmp/vo-lines.json.

The JSON is the VO script: clip key -> the exact line that was recorded in the
studio voice (see narration.ts). Values are emitted with json.dumps, so the TS
file is double-quoted and every apostrophe, quote and backslash escapes itself
correctly no matter what the copy says.

    python scripts/build-vo-lines.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, 'scripts', 'tmp', 'vo-lines.json')
TARGET = os.path.join(ROOT, 'src', 'voLines.ts')
CLIPS = os.path.join(ROOT, 'src', 'assets', 'audio', 'vo')

lines = json.load(open(MANIFEST, encoding='utf8'))

missing = [key for key in lines if not os.path.exists(os.path.join(CLIPS, key + '.mp3'))]
extra = [
    name[:-4] for name in sorted(os.listdir(CLIPS))
    if name.endswith('.mp3') and name[:-4] not in lines
]

out = [
    '// GENERATED by scripts/build-vo-lines.py from scripts/tmp/vo-lines.json.',
    '// Voice: "Suhana J" via ElevenLabs eleven_multilingual_v2 - see narration.ts.',
    '// Each entry maps a VO clip key to the EXACT in-game line it records, so',
    '// narrate() can match a line to its recording by text as well as by key.',
    "const clips = import.meta.glob('./assets/audio/vo/*.mp3', "
    "{ eager: true, query: '?url', import: 'default' }) as Record<string, string>",
    '',
    'export const VO_TEXTS: Record<string, string> = {',
]
for key, text in lines.items():
    out.append('  ' + json.dumps(key) + ': ' + json.dumps(text) + ',')
out += [
    '}',
    '',
    '/** clip key -> bundled mp3 url */',
    'export const VO_URLS: Record<string, string> = {}',
    'for (const [path, url] of Object.entries(clips)) {',
    "  const key = path.split('/').pop()!.replace(/[.]mp3$/, '')",
    '  VO_URLS[key] = url',
    '}',
]
open(TARGET, 'w', encoding='utf8').write('\n'.join(out) + '\n')

print('voLines.ts: %d lines of script' % len(lines))
if missing:
    print('  NO CLIP RECORDED for: %s' % ', '.join(missing))
if extra:
    print('  clips with no script entry: %s' % ', '.join(extra))
