// GENERATED by scripts/build-vo-lines.py from scripts/tmp/vo-lines.json.
// Voice: "Suhana J" via ElevenLabs eleven_multilingual_v2 - see narration.ts.
// Each entry maps a VO clip key to the EXACT in-game line it records, so
// narrate() can match a line to its recording by text as well as by key.
const clips = import.meta.glob('./assets/audio/vo/*.mp3', { eager: true, query: '?url', import: 'default' }) as Record<string, string>

export const VO_TEXTS: Record<string, string> = {
  "clue-SCOOTER": "A parked scooter is blocking part of your lane. Choose what the car should do, then test your rule.",
  "clue-NARROW": "The road narrows to a small gap. Your car must fit through. Choose what the car should do, then test your rule.",
  "clue-ARRIVED": "You reached the clinic. The parcel is still in the car. Choose what the car should do, then test your rule.",
  "clue-MOVING": "A child is crossing the road in front of you. Choose what the car should do, then test your rule.",
  "clue-MANY_MOVING": "People are still using the crossing. Choose what the car should do, then test your rule.",
  "clue-CYCLIST": "A cyclist is ahead. There is no safe space to overtake. Choose what the car should do, then test your rule.",
  "clue-DOG": "The dog has not noticed your quiet car. Choose what the car should do, then test your rule.",
  "clue-ROAD_WET": "The road is wet. The car needs more space to stop. Choose what the car should do, then test your rule.",
  "clue-FOG": "Fog makes it hard to see the road ahead. Choose what the car should do, then test your rule.",
  "clue-EMERGENCY_BEHIND": "An ambulance behind you needs a clear path. Choose what the car should do, then test your rule.",
  "clue-ROAD_BLOCKED": "A person is facing away from the car. Choose what the car should do, then test your rule.",
  "clue-DEAD_END": "Barriers block the whole road. Choose what the car should do, then test your rule.",
  "why-SCOOTER-1": "The scooter is parked. The car checks the space and goes slowly around it.",
  "why-SCOOTER-2": "This scooter stays parked during the game. Waiting does not clear the road.",
  "why-SCOOTER-3": "The car goes too fast to turn safely around the scooter.",
  "why-NARROW-1": "The car lines up with the gap, then drives through slowly.",
  "why-NARROW-2": "The gap is small. At this speed, the car cannot steer through safely.",
  "why-NARROW-3": "The car fits through the gap. Turning away leaves the delivery unfinished.",
  "why-ARRIVED-1": "The car needs a rule that tells it to stop and give the parcel at the clinic.",
  "why-ARRIVED-2": "The car drives past with the parcel still inside. It needs to stop here.",
  "why-ARRIVED-3": "The clinic needs the parcel. Going home leaves the job unfinished.",
  "why-MOVING-1": "The car stops before the child, waits for them to cross, then drives on.",
  "why-MOVING-2": "The child is still crossing. The car must wait for the road to clear.",
  "why-MOVING-3": "Beeping does not keep the child out of the way. The car needs to stop.",
  "why-MANY_MOVING-1": "The car waits until every person has crossed before it moves again.",
  "why-MANY_MOVING-2": "People are still crossing. Driving between them leaves too little space.",
  "why-MANY_MOVING-3": "The people need time to cross. Beeping does not clear the road.",
  "why-ROAD_WET-1": "The wet road is slippery. The car slows earlier and leaves more space to stop.",
  "why-ROAD_WET-2": "The wet road needs more stopping space. The old speed does not leave enough.",
  "why-ROAD_WET-3": "The wheels can slip on the wet road. Going faster makes stopping harder.",
  "why-EMERGENCY_BEHIND-1": "The car does two things in order: moves out of the lane, then stops safely.",
  "why-EMERGENCY_BEHIND-2": "The car stops in the lane, so the ambulance still cannot get past.",
  "why-EMERGENCY_BEHIND-3": "The car stays in the ambulance\u2019s way. It needs to make space instead.",
  "why-CYCLIST-1": "The car stays behind the bicycle with a safe gap. There is no room to pass here.",
  "why-CYCLIST-2": "Beeping does not make the lane wider. There is still no room to pass.",
  "why-CYCLIST-3": "The car gets too close to the bicycle. It needs to stay behind.",
  "why-DOG-1": "The car stops first. In this game, one beep gets the dog\u2019s attention. The car waits until it moves away.",
  "why-DOG-2": "Stopping protects the dog. In this scene, the dog also needs a sound to notice the car.",
  "why-DOG-3": "The dog could step into the car\u2019s path. The car needs to stop first.",
  "why-ROAD_BLOCKED-1": "The person hears the beep and steps aside. The car waits until the lane is clear.",
  "why-ROAD_BLOCKED-2": "In this scene, the person has not noticed the quiet car. Waiting alone does not get their attention.",
  "why-ROAD_BLOCKED-3": "There is a way forward once the person moves. Turning back leaves the delivery unfinished.",
  "why-FOG-1": "The car slows because it cannot see far ahead. A short beep lets the person hear it.",
  "why-FOG-2": "The fog hides the road ahead. At this speed the car sees the obstacle too late.",
  "why-FOG-3": "The car cannot see what is ahead. Driving faster gives it less time to stop.",
  "why-DEAD_END-1": "The barriers block the whole road. The car turns back to find another route.",
  "why-DEAD_END-2": "These barriers stay in place during the game. Waiting does not open the road.",
  "why-DEAD_END-3": "The barriers cannot hear a horn or move out of the way.",
  "why-SENSORS-1": "This is what the car has now. Nothing points backwards \u2014 so to the car, the ambulance does not exist.",
  "why-SENSORS-2": "No help here. The ambulance is directly behind \u2014 side sensors spot it too late.",
  "why-SENSORS-3": "Right. Now the car can see behind it \u2014 and now a rule about it can work.",
  "retry": "Use what you saw. Pick a different action and test it.",
  "sensor-fitted": "Rear sensor fitted! Now choose how to make room for the ambulance.",
  "report-signoff": "Policy approved.",
  "tutorial-1": "Your car can drive, but it cannot think. A medical parcel has to reach the clinic on Fenner Street, and the car's rulebook is corrupted. It is empty. A self-driving car does only what its rules tell it to do, so when it meets something it has no rule for, it stops in the road and asks your crew what to do.",
  "tutorial-2": "A rule is an IF, THEN sentence. IF is the situation: something the car's sensors can actually see. If the sensors cannot see it, no rule can help. THEN is the action, what the car will do about it, every single time, without asking again. Test a rule and get it right, and it is written into the car's brain for the rest of the whole run.",
  "tutorial-3": "Here is how the car reads its rules. Every time something happens, it starts at rule one and reads down the list. The first rule whose IF matches is the one it runs, and then it stops reading. So a rule that is too broad can swallow a situation you meant a later rule to handle. If the car does the wrong thing, your rule may be right, but in the wrong place.",
  "tutorial-4": "Your turn has four steps. Look: the car stops and the popup shows what its sensors picked up. Choose one of the three IF THEN cards, and talk it over with your crew before you commit. Test it with the big key at the bottom, and the car does exactly what your card said. Then learn: if it worked, the rule is saved. If it crashed, nobody is hurt. You see why, and you get another go.",
  "tutorial-5": "The wheel comes round to everybody. One challenge each, in order, and then round again. The popup always names whose turn it is, and when a challenge is solved, the key tells you who to pass the controls to. Only the player at the wheel picks the card, but everybody helps think, and the whole crew drives the final delivery together.",
}

/** clip key -> bundled mp3 url */
export const VO_URLS: Record<string, string> = {}
for (const [path, url] of Object.entries(clips)) {
  const key = path.split('/').pop()!.replace(/[.]mp3$/, '')
  VO_URLS[key] = url
}
